### ISSUE TITLE
docker build failed: mujoco invalid activation key

### ISSUE THREAD

**Issue by zhackzey** [snasiriany/leap#1]
I obtained mjkey.txt and I'm assured that it's valid. However, after moving it into the correct directory, during docker build process, which in "python -c 'import mujoco_py '", it shows 'ERROR: Invalid activation key'. I'm confused about this problem. 
Is there any alternative method to run experiments without building and using docker? Thank you very much!

**Comment by snasiriany** [comment]
Hi, I'd say setting up the environment without docker is very challenging. But if you're interested, you could look at the dockerfile and try to build the same dependencies as in the docker file.

Mujoco keys recently expired, which means that you will have to rebuild the docker image from scratch, with the new key. Please make sure to clear any cache you have of the docker image, and then remake it with the new key.
