### ISSUE TITLE
Mujoco Activation Key in Docker 

### ISSUE THREAD

**Issue by juliusfrost** [snasiriany/leap#2]
Hi, 

I was trying to reproduce your code but it seems that mujoco will not work in docker for me. You need an institutional license but I only have a free student version (see http://www.mujoco.org/forum/index.php?threads/getid_linux-outputs-different-machine-id-in-docker-container.3848/). Is it possible to get this to run without docker?

**Comment by snasiriany** [comment]
Hi,

My apologies for the delayed response. Yes, this is possible. You can run all the experiments in local mode, by specifying the tag `--mode local` when running any scripts. You can look through the docker file (https://github.com/snasiriany/leap/blob/master/docker/Dockerfile) to see the key dependencies, in particular the lines that have `pip install ... `
