### ISSUE TITLE
How to visualize all subgoals from start to final goal? 

### ISSUE THREAD

**Issue by HyeongYeolRyu** [snasiriany/leap#4]
Thank you for your excellent research work, I have a question about visualizing all subgoals as shown on your website(https://sites.google.com/view/goal-planning/) like the GIFs bottom of the page.
I did all experiments through step1~step4, but I could only have samples and reconstructions images.

**Comment by snasiriany** [comment]
Hello!

There are a host of different items that you can visualize, which are enumerated as a list in [this line](https://github.com/snasiriany/leap/blob/4d75961ff2ff203d4412633cbeb12889de3c79b6/railrl/misc/video_gen.py#L49).

You can enable which items [you want](https://github.com/snasiriany/leap/blob/master/experiments/state/test_tdm_state.py#L78), and which items you [don't want](https://github.com/snasiriany/leap/blob/master/experiments/state/test_tdm_state.py#L81), in the experiment script. Specifically, for visualizing the current next subgoal in the video, you can enable the `image_desired_subgoal_reproj` option in `vis_list.` If you would like to see a sequence of subgoals that are planned, side by side in one image, you can enable `image_desired_subgoals_reproj` in `vis_list`.

Note: you may have to add or remove a the text `image_` before a keyword, to make things work. I think it depends on the key being used.

I hope this helps!

**Comment by HyeongYeolRyu** [comment]
Thank you for the detailed explanation! I tried all the possible cases, however, none of them work though I trained 'pnr' and tested it with all vis_list items...
I still get only 'r.png' and 's.png' and some 'video_n.mp4'. Do you think are there any other issues?

Thanks.

**Comment by snasiriany** [comment]
Hi,

Did you make sure to remove all the items from `vis_blacklist` [here](https://github.com/snasiriany/leap/blob/master/experiments/state/test_tdm_state.py#L81)?

Also, what are the contents of `video_n.mp4`? How many rows do you see? Usually, for any new item that you add to `vis_list`, there should be an extra row in `video_n.mp4` corresponding to that item.

The exception here is `image_desired_subgoals_reproj`, which will produce an extra `sg_n.png` file, and that is implemented [here](https://github.com/snasiriany/leap/blob/4d75961ff2ff203d4412633cbeb12889de3c79b6/railrl/misc/video_gen.py#L123) in the code.

If you aren't able to see the desired behavior you're looking for, I would place a print statement at the beginning of [this function](https://github.com/snasiriany/leap/blob/4d75961ff2ff203d4412633cbeb12889de3c79b6/railrl/misc/video_gen.py#L31), to see what the inputs `vis_list` and `vis_blacklist` are.

Also, please keep in mind that the code does not have visualizations that produce the exact gifs on the website. Those gifs were created using video editing software. But the code should be able to produce the individual components seen in those gifs (eg. current observation, goal, current subgoal) in some shape or form.

**Comment by HyeongYeolRyu** [comment]
Thank you!
I finally found the problem and have fixed. As you explained, I printed each of the statements and found that no 'vis_list' items were passed as a parameter. (I noticed the result of subgoals was not exactly video as I already checked the code that save an image)
Anyway, now it works well. 
Thank you so much!
