### ISSUE TITLE
multiworld leap branch sawyer_push_nips environment set_env_state

### ISSUE THREAD

**Issue by yilin-wu98** [snasiriany/leap#6]
Hi Soroush,

Sorry to bother you again. I am opening this new issue because I have some questions about the multiworld environment in your experiments. I am trying to use your push_and_reach environment in the multiworld repo leap branch. I find in the sawyer_push_nips.py, the `set_env_state` function is rewritten but compared to the original one in the master branch,  the line `self.sim.forward()` is missing. 
I think in the environment, we need the `sim.forward()` to do the simulation and so that the state we pass to the function is actually set by the environment. Therefore, I am wondering why the `sim.forward` isn't in the `set_env_state` function. Or do you actually call some other function somwhere else to achieve the same effect as `sim.forward` but I fail to notice? 
![set_state_leap](https://user-images.githubusercontent.com/46740313/98342148-f5e49880-204a-11eb-94e9-a55e9da16a60.PNG)

**Comment by snasiriany** [comment]
Hi Yilin,

That's a good catch! I think we should add sim.forward right at the end of the function, but I'm not actually sure if it's strictly needed. Is the code (without the sim.forward) leading to unexpected issues? If I recall correctly, it still worked as intended even without this call. If it does cause issues, I would add the sim.forward just to be safe.

Update: it seems everything was correct already. See message below.

**Comment by snasiriany** [comment]
Actually, looks like the original code without the explicit sim.forward call is correct. `set_to_env_state` calls `set_goal` which in turn calls the `set_state` function in [mujoco_env.py](https://github.com/vitchyr/multiworld/blob/leap/multiworld/envs/mujoco/mujoco_env.py#L91). That function in turn calls `sim.forward`. So we are calling sim.forward after all :)

**Comment by yilin-wu98** [comment]
Thanks for replying! I think I forgot to check if the set_goal function calls `sim.forward` to achieve the same result.
